### ISSUE TITLE
请教：per.py中有一个小错误（？）

### ISSUE THREAD

**Issue by ltc013** [deep-reinforcement-learning-book/Chapter4-DQN#9]
![image](https://user-images.githubusercontent.com/100110620/156328305-ff1a42bb-c2ce-4ee5-98b6-c3ff2ddd794e.png)
请问这个问题是否成立，谢谢！

**Comment by Officium** [comment]
你好，128行的`end -= 1`确实是个bug，在per中会导致计算weight时少考虑一个元素，感谢！

**Comment by Officium** [comment]
fixed in commit https://github.com/deep-reinforcement-learning-book/Chapter4-DQN/commit/b359a8910197861dc436b3ce031cfacbe43f05fe
